---
language: python
services:
 - docker
install:
 - python -m pip3 install molecule docker
 - python -m pip3 install flake8
 - python -m pip3 install yamllint

script:
 - molecule --version
 - ansible --version
 - molecule lint
