---
language: python
services:
  - docker
install:
  - python3 -m pip install ansible
  - python3 -m pip install molecule
  - python3 -m pip3 install flake8
  - python3 -m pip3 install yamllint
  - docker -v
  - python3 -v
  - ansible --version
  - molecule --version
  - ansible-lint --version
script:
  - molecule --version
  - ansible --version
  - molecule lint
  - molecule test
