---
language: python
services:
  - docker
before_install:
  - chmod +x ./travis_merge.sh
install:
  - python3 -m pip install molecule[ansible,docker,lint]
script:
  - molecule --version
  - molecule converge
after_success:
  - ./travis_merge.sh
