---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: centos:8
    pre_build_image: true
lint: |
  set -e
  yamllint --format colored .
  ansible-lint --force-color
  flake8
provisioner:
  name: ansible
verifier:
  name: ansible
